name: VanillaSurvivalGames
main: com.simonorj.mc.VanillaSurvivalGames.VanillaSurvivalGames
version: {$VersionNumber}
author: SimonOrJ
commands:
  game:
    aliases: [games,tag,hideandseek]
    description: Vanilla-friendly tag game.
    usage: /games [create|join|leave|it|seeker|invite|reset]
